LIBDRUM-1038. Fixes for Angular compile errors
Fixed Angular compile errors when running `npm run start:dev`.

* src/themes/mdsoar/app/home-page/home-news/home-news.component.scss

```
./src/themes/mdsoar/app/home-page/home-news/home-news.component.scss?ngResource - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
    ╷
119 │ ┌     @include hover {
120 │ │       color: var(--ds-home-news-link-hover-color);
121 │ └     }
    ╵
  src/themes/mdsoar/app/home-page/home-news/home-news.component.scss 119:5  root stylesheet
```

Fixed by changing `@include hover` to simply `&:hover`.

This was due to the Bootstrap 4 to Bootstrap 5 update, which removed the
“hover” mixin.

* src/themes/mdsoar/styles/_theme_sass_variable_overrides.scss

```
./src/themes/mdsoar/styles/theme.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $n: Invalid index 1 for a list with 0 elements.
  ╷
7 │   @if type-of($values) == "string" or type-of(nth($values, 1)) != "list" {
  │                                               ^^^^^^^^^^^^^^^
  ╵
```

This was caused by an empty list which confused the Bootstrap 5 parser

```
$theme-colors: (
  // ...
);
```

Fixed by comparing to
“src/themes/dspace/styles/_theme_sass_variable_overrides.scss”, and took
all changes (no UMD customizations) some of which had changed in
DSpace 8.

https://umd-dit.atlassian.net/browse/LIBDRUM-1038